-- 以下のテーブルとデータをあらかじめrpgdbに投入しておく必要があります

DROP TABLE IF EXISTS MONSTERS;
CREATE TABLE MONSTERS(NAME VARCHAR(255) PRIMARY KEY, HP INT, MP INT, EXP INT);
INSERT INTO MONSTERS VALUES('スライム', 15, 7, 9);
INSERT INTO MONSTERS VALUES('デスバット', 29, 11, 15);
INSERT INTO MONSTERS VALUES('鬼将軍', 87, 99, 76);
SELECT * FROM MONSTERS ORDER BY HP;

DROP TABLE IF EXISTS WEAPONS;
CREATE TABLE WEAPONS(NAME VARCHAR(255) PRIMARY KEY, ATK INT);
INSERT INTO WEAPONS VALUES('ひのきの棒', 3);
INSERT INTO WEAPONS VALUES('こんぼう', 7);
SELECT * FROM WEAPONS ORDER BY HP;